apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-postgresql
  namespace: sparkyfitness
  labels:
    app.kubernetes.io/name: sparkyfitness
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi

