---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab
theme: dark
color: slate
headerStyle: clean
target: _blank
favicon: ./favicon/favicon.ico

pwa:
  icons:
    - src: ./favicon/favicon.png
      sizes: 192x192
      type: image/png
    - src: ./favicon/favicon.png
      sizes: 512x512
      type: image/png

layout:
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Links:
    style: row
    columns: 3
