apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik-k3s.devnord.duckdns.org`)
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: letsencrypt
